# Generated by Django 2.0 on 2017-12-25 15:01

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=homepage.models.dish_img_path)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(help_text='How does this dish taste?', verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='DishInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New dish'), ('S', 'Saling'), ('O', 'Out saled')], max_length=2)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='ResInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(help_text='Where is this restaurant?')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to=homepage.models.restaurant_logo_path)),
                ('desc', models.TextField(help_text='Restaurant description', verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='resinstance',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.Restaurant'),
        ),
    ]
