# Generated by Django 2.0 on 2017-12-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resinstance',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resinstance',
            name='telephone',
            field=models.CharField(default=1, help_text='telephone number', max_length=100),
            preserve_default=False,
        ),
    ]
