# Generated by Django 2.0 on 2017-12-25 15:32

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171225_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinstance',
            name='grade',
            field=models.IntegerField(default=0, validators=[homepage.models.validate_grade]),
        ),
    ]
